name: Pull Request Check

on: pull_request

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: check fmt
        run: |
          go fmt ./...
          echo "==> Checking that code complies with go fmt requirements..."
          git diff --exit-code

      - name: check lint
        run: |
          echo "==> Updating linter dependencies..."
          curl -sSfL -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          echo "==> Running linter on all Go source files..."
          GO111MODULE=on golangci-lint run ./... --timeout 5m

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: test
        run: make testacc
        env:
          TEST_GIT_USERNAME: git
          TEST_GIT_TOKEN: ${{ secrets.TEST_GIT_TOKEN }}

      - name: print logs
        if: always()
        run: |
          find ./provisioner -name '*.txt' | xargs cat
